config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::extensions(['html', 'json']);

Router::scope('/', function ($routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    // $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/', ['controller' => 'Orders', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});


/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Product.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\I18n\Time;
use Cake\I18n\Number;

/**
 * Product Entity.
 *
 * @property int $id
 * @property string $name
 * @property string $sku
 * @property string $unit
 * @property float $price
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 * @property \Cake\I18n\Time $deleted
 * @property \App\Model\Entity\Order[] $orders
 * @property \App\Model\Entity\Quote[] $quotes
 */
class Product extends BaseEntity
{
    protected $prefix = 'PROD-';

    protected function _getIdentifier(){
        $string = $this->id_formatted;
        if(isset($this->sku)) {
            $string .= sprintf(" - %s", $this->sku);
        }
        $string .= sprintf(" - %s", $this->name);
        if(isset($this->unit)) {
            $string .= sprintf(" (%s)", $this->unit);
        }
        return $string;
    }

    protected function _getPriceFormatted(){
        return Number::currency($this->price);
    }
}

src/Template/Cell/ProductSelector/display.ctp
<div style="display: none">
    <select id="products-base">
    <option value=""></option>
    <?php
        if(isset($products)) :
            foreach ($products as $product):
    ?>
    <option value="<?= $product->name ?>" product-id="<?= $product->id ?>" product-name="<?= $product->name ?>" product-sku="<?= $product->sku ?>" product-price="<?= $product->price ?>">
        <?= h($product->identifier) ?>
    <?php
            endforeach;
        endif;
    ?>
    </select>
</div>

<script>
(function($) {
    $(document).ready(function() {
        $('body').on('DOMSubtreeModified', function() {
            $('<?= $target ?>').each(function(i, el) {
                var did = $(el).data('did');
                if(!did) {
                    var target = $(el);
                    var attributes = target.prop('attributes');
                    var select = $('select#products-base').eq(0).clone().data('did', true);

                    $.each(attributes, function() {
                        select.attr(this.name, this.value);
                    });
                    target.replaceWith(select);

                    select
                        .chosen({
                            no_results_text: "=("
                        })
                        .on('change', function(e) {
                            var that = $(e.currentTarget);
                            var selected = $(e.currentTarget.selectedOptions[0]);
                            var sheet = $('#dynamic').calx('getSheet');

                            var elId = selected.parents('tr').find('.product-id');
                            var elPrice = selected.parents('tr').find('.product-price');

                            var cellId = $('#dynamic').calx('getCell', elId.attr('data-cell'));
                            var cellPrice = $('#dynamic').calx('getCell', elPrice.attr('data-cell'));

                            elId.val(selected.attr('product-id'));
                            cellId.setValue(selected.attr('product-id'));

                            cellPrice.setValue(selected.attr('product-price'));
                            elPrice.val(selected.attr('product-price'));

                            setTimeout(function() {
                                elId.trigger('change');
                                elPrice.trigger('change');
                                sheet.calculate();
                            }, 500);
                        });
                }
            });
        });
    });
})(jQuery);
</script>