config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::extensions(['html', 'json']);

Router::scope('/', function ($routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    // $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/', ['controller' => 'Orders', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});


/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/BaseEntity.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\I18n\Time;
use Cake\I18n\Number;

/**
 * Product Entity.
 *
 * @property int $id
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 * @property \Cake\I18n\Time $deleted
 */
class BaseEntity extends Entity
{
    protected $prefix = '';

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    protected function _getIdFormatted(){
        $mininum = 5;
        $size = strlen($this->id) > $mininum ? strlen($this->id) + 1 : $mininum;
        return $this->prefix . str_pad($this->id, $size, '0', STR_PAD_LEFT);
    }

    protected function _getCreatedFormatted(){
        return (new Time($this->created))->i18nFormat([\IntlDateFormatter::SHORT, \IntlDateFormatter::NONE]);
    }

    protected function _getModifiedFormatted(){
        return (new Time($this->created))->i18nFormat([\IntlDateFormatter::SHORT, \IntlDateFormatter::NONE]);
    }
}

src/Model/Entity/Product.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\I18n\Time;
use Cake\I18n\Number;

/**
 * Product Entity.
 *
 * @property int $id
 * @property string $name
 * @property string $sku
 * @property string $unit
 * @property float $price
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 * @property \Cake\I18n\Time $deleted
 * @property \App\Model\Entity\Order[] $orders
 * @property \App\Model\Entity\Quote[] $quotes
 */
class Product extends BaseEntity
{
    protected $prefix = 'PROD-';

    protected function _getIdentifier(){
        $string = $this->id_formatted;
        if(isset($this->sku)) {
            $string .= sprintf(" - %s", $this->sku);
        }
        $string .= sprintf(" - %s", $this->name);
        if(isset($this->unit)) {
            $string .= sprintf(" (%s)", $this->unit);
        }
        return $string;
    }

    protected function _getPriceFormatted(){
        return Number::currency($this->price);
    }
}

src/Model/Entity/Quote.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\I18n\Time;
use Cake\I18n\Number;

/**
 * Quote Entity.
 *
 * @property int $id
 * @property int $client_id
 * @property \App\Model\Entity\Client $client
 * @property float $final_price
 * @property float $amount_advanced
 * @property float $discount
 * @property \Cake\I18n\Time $expire_date
 * @property \Cake\I18n\Time $exit_date
 * @property string $location
 * @property string $warranty
 * @property string $data
 * @property \Cake\I18n\Time $accepted
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $deleted
 */
class Quote extends BaseEntity
{
    protected $prefix = 'QUO-';

    protected function _getFinalPriceFormatted(){
        return Number::currency($this->final_price);
    }

    protected function _getAmountAdvancedFormatted(){
        return Number::currency($this->amount_advanced);
    }

    protected function _getDiscountFormatted(){
        return Number::toPercentage($this->discount);
    }

    protected function _getExpireDateFormatted(){
        return (new Time($this->expire_date))->i18nFormat([\IntlDateFormatter::SHORT, \IntlDateFormatter::NONE]);
    }

    protected function _getExitDateFormatted(){
        return (new Time($this->exit_date))->i18nFormat([\IntlDateFormatter::SHORT, \IntlDateFormatter::NONE]);
    }

    protected function _getAcceptedFormatted(){
        return (new Time($this->accepted))->i18nFormat([\IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT]);
    }

    public function isAccepted(){
        return !is_null($this->accepted);
    }

    public function becameOrder(){
        return !is_null($this->order_id);
    }

    public function hasDiscount(){
        return $this->discount > 0;
    }

}

src/Controller/QuotesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\I18n\Time;
use Cake\Network\Exception\MethodNotAllowedException;

/**
 * Quotes Controller
 *
 * @property \App\Model\Table\QuotesTable $Quotes
 */
class QuotesController extends AppController
{

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Clients'],
            'quote' => [
                'Quotes.id' => 'desc'
            ]
        ];
        $this->set('quotes', $this->paginate($this->Quotes));
        $this->set('_serialize', ['quotes']);
    }

    /**
     * View method
     *
     * @param string|null $id Quote id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $quote = $this->Quotes->get($id, [
            'contain' => ['Clients']
        ]);
        $this->set('quote', $quote);
        $this->set('_serialize', ['quote']);
    }

    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $quote = $this->Quotes->newEntity();
        if ($this->request->is('post')) {
            $quote = $this->Quotes->patchEntity($quote, $this->request->data);
            if ($this->Quotes->save($quote)) {
                $this->Flash->success(__('The quote has been saved.'));
                $this->Quotes->generatePdf($quote);
                return $this->redirect(['action' => 'view', $quote->id]);
            } else {
                $this->Flash->error(__('The quote could not be saved. Please, try again.'));
            }
        }
        $clients = $this->Quotes->Clients->find('list', ['limit' => 200, 'valueField' => 'identifier']);
        $this->set(compact('quote', 'clients'));
        $this->set('_serialize', ['quote']);
    }

    /**
     * Generate PDF method
     *
     * @return void Redirects on successful generation, renders view otherwise.
     */
    public function generatePdf($id = null)
    {
        // $this->request->allowMethod(['patch', 'post', 'put']);

        $quote = $this->Quotes->get($id, [
            'contain' => []
        ]);
        if ($this->Quotes->generatePdf($quote)) {
            $this->Flash->success(__('The PDF quote has been generated.'));
        } else {
            $this->Flash->error(__('The PDF quote could not be generated. Please, try again.'));
        }
        return $this->redirect(['action' => 'view', $quote->id]);
    }

    /**
     * Edit method
     *
     * @param string|null $id Quote id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        //Nobody can edit
        throw new MethodNotAllowedException(__('This action is not allowed'));

        //But nothing remains forever
        $quote = $this->Quotes->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $quote = $this->Quotes->patchEntity($quote, $this->request->data);
            if ($this->Quotes->save($quote)) {
                $this->Flash->success(__('The quote has been saved.'));
                return $this->redirect(['action' => 'view', $quote->id]);
            } else {
                $this->Flash->error(__('The quote could not be saved. Please, try again.'));
            }
        }
        $clients = $this->Quotes->Clients->find('list', ['limit' => 200]);
        $this->set(compact('quote', 'clients'));
        $this->set('_serialize', ['quote']);
    }

    /**
     * Set as accepted method
     *
     * @param string|null $id Quote id.
     * @return \Cake\Network\Response|null Redirects to view.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function setAsAccepted($id = null)
    {
        $quote = $this->Quotes->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $quote = $this->Quotes->get($id);
            if ($this->Quotes->setAsAccepted($quote)) {
                $this->Flash->success(__('The quote has been saved.'));
                return $this->redirect(['action' => 'view', $id]);
            } else {
                $this->Flash->error(__('The quote could not be saved. Please, try again.'));
            }
        }
        return $this->redirect(['action' => 'view', $quote->id]);
    }

    /**
     * Generate order method
     *
     * @param string|null $id Quote id.
     * @return \Cake\Network\Response|null Redirects to Order::add.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function generateOrder($id = null)
    {
        if ($this->request->is(['patch', 'post', 'put'])) {
            $quote = $this->Quotes->get($id);
            if ($this->Quotes->setAsAccepted($quote)) {
                return $this->redirect(['controller' => 'Orders', 'action' => 'add', '?' => ['from_quote' => $id]]);
            } else {
                $this->Flash->error(__('The order could not be generated. Please, set the quote as accepted first.'));
            }
        }
        return $this->redirect(['action' => 'view', $quote->id]);
    }

    /**
     * Delete method
     *
     * @param string|null $id Quote id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $quote = $this->Quotes->get($id);
        if ($this->Quotes->delete($quote)) {
            $this->Flash->success(__('The quote has been deleted.'));
        } else {
            $this->Flash->error(__('The quote could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Quotes/as_pdf_example.ctp
<?php

// use Cake\Routing\Router;

$this->extend('../Layout/TwitterBootstrap/dashboard');
$this->start('tb_actions');
?>
<li><?= $this->Form->postLink(__('Delete Order'), ['action' => 'delete', $order->id], ['confirm' => __('Are you sure you want to delete # {0}?', $order->id)]) ?> </li>
<li><?= $this->Html->link(__('New Order'), ['controller' => 'Orders', 'action' => 'add']) ?> </li>
<?php $this->end(); ?>
<?php $this->assign('tb_sidebar', '<ul class="nav nav-sidebar">' . $this->fetch('tb_actions') . '</ul>'); ?>

<?php
use Cake\Routing\Router;
use Cake\Core\Configure;

$path = Configure::read('App.wwwRoot');

?>

<table width="100%" style="border:solid 1px">
    <tbody>
        <tr>
            <td colspan="6" style="text-align:center;">
                Informações do Emitente
            </td>
        </tr>
        <tr>
            <td colspan="6" style="text-align:center;">
                <img src="<?php echo Router::url('/img/hai.logo.dark.png') ?>" alt="Logo Hai Tecnologia" class="logo">
            </td>
        </tr>
        <tr>
            <td colspan="6" style="text-align:center;">
                Hai- Soluções em Tecnologia <br>
                Rua Quatorze de Junho,74-Buritis,30575-350 <br>
                Belo Horizonte-MG Fone:(31)9244-9495 <br>
                <a href="http://www.haitecnologia.com">www.haitecnologia.com</a> <br>
            </td>
        </tr>
    </tbody>
</table>
<table width="100%" border="1">
    <caption>DESTINAT&Aacute;RIO/REMETENTE:</caption>
    <tbody>
        <tr>
            <td colspan="3" class="no border bottom">NOME/RAZ&Atilde;O SOCIAL:&nbsp;</td>
            <td class="no border bottom">CPF/CNPJ:</td>
            <td colspan="2" class="no border bottom">DATA DA EMISS&Atilde;O:</td>
        </tr>
        <tr>
            <td colspan="3" class="no border top value"><?= h($order->client->name) ?></td>
            <td class="no border top value"><?= h($order->individual_registration_formatted) ?></td>
            <td colspan="2" class="no border top value"><?= h($order->created_formatted) ?></td>
        </tr>
        <tr>
            <td colspan="2" class="no border bottom">ENDERE&Ccedil;O:</td>
            <td class="no border bottom">BAIRRO:</td>
            <td class="no border bottom">CEP:</td>
            <td colspan="2" class="no border bottom">DATA DE SA&Iacute;DA:</td>
        </tr>
        <tr>
            <td colspan="2" class="no border top value"><?= h($order->client->address) ?></td>
            <td class="no border top value"><?= h($order->client->district) ?></td>
            <td class="no border top value"><?= h($order->client->zipcode_formatted) ?></td>
            <td colspan="2" class="no border top value"><?= $order->exit_date_formatted ?></td>
        </tr>
        <tr>
            <td class="no border bottom">MUNIC&Iacute;PIO:</td>
            <td class="no border bottom">UF:</td>
            <td class="no border bottom">FONE/FAX:</td>
            <td colspan="3" class="no border bottom">INSCRI&Ccedil;&Atilde;O ESTADUAL</td>
        </tr>
        <tr>
            <td class="no border top value"><?= h($order->client->city) ?></td>
            <td class="no border top value"><?= h($order->client->state) ?></td>
            <td class="no border top value"><?= h($order->client->phone1) ?></td>
            <td colspan="3" class="no border top value"><?= h($order->client->state_registration) ?></td>
        </tr>
    </tbody>
</table>
<table width="100%" border="1">
    <caption>FATURA/DUPLICATA:</caption>
    <tbody>
        <tr>
            <td width="100">N&Uacute;MERO:</td>
            <td colspan="5" class="value"><?= h($order->id_formatted) ?></td>
        </tr>
        <tr>
            <td>VENCIMENTO:</td>
            <td colspan="5" class="value"><?= h($order->expire_date_formatted) ?></td>
        </tr>
        <tr>
            <td>VALOR:</td>
            <td colspan="5" class="value"><?= h($order->final_price_formatted) ?></td>
        </tr>
    </tbody>
</table>
<table width="100%" border="1">
    <caption>DADOS DOS PRODUTOS:</caption>
    <tbody>
        <tr style="text-align:center;">
            <td>C&Oacute;DIGO:</td>
            <td>DESCRI&Ccedil;&Atilde;O:</td>
            <td>QUANTIDADE:</td>
            <td>VALOR UNIT:</td>
            <td>DESCONTO:</td>
            <td>VALOR TOTAL:</td>
        </tr>
        <?php
            echo $this->Html->tableCells($order->data);
        ?>
    </tbody>
</table>
<table width="100%" border="1">
    <caption>DADOS ADICIONAIS:</caption>
    <tbody>
        <tr>
            <td>LOCAL DO SERVI&Ccedil;O:</td>
            <td>GARANTIA:</td>
        </tr>
        <tr>
            <td width="50%">
                <p class="padding-20">
                <?= h($order->location) ?>
                </p>
            </td>
            <td>
                <p class="padding-20">
                <?= h($order->warranty) ?>
                </p>
            </td>
        </tr>
    </tbody>
</table>
<table width="100%" border="1" style="text-align: center;">
    <caption style="text-align: center;">*N&Atilde;O &Eacute; NOTA FISCAL, APENAS RECIBO</caption>
    <tbody>
        <tr>
            <td colspan="6" style="text-align: center;">
                <p>ASSINATURA INSTALADOR:</p>
                <p>&nbsp;</p>
                <hr style="width:90%;margin:auto;border:solid 1px">
            </td>
        </tr>
    </tbody>
</table>

src/Template/Quotes/index.ctp
<?php

use \Cake\I18n\Time;

$this->extend('../Layout/TwitterBootstrap/dashboard');
$this->start('tb_actions');
?>
    <li><?= $this->Html->link(__('New Quote'), ['action' => 'add']); ?></li>
<?php $this->end(); ?>
<?php $this->assign('tb_sidebar', '<ul class="nav nav-sidebar">' . $this->fetch('tb_actions') . '</ul>'); ?>

<table class="table table-striped" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th><?= $this->Paginator->sort('id'); ?></th>
            <th><?= $this->Paginator->sort('client_id'); ?></th>
            <th><?= $this->Paginator->sort('final_price'); ?></th>
            <th><?= $this->Paginator->sort('expire_date'); ?></th>
            <th><?= $this->Paginator->sort('paid'); ?></th>
            <th class="actions"><?= __('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($quotes as $quote): ?>
        <tr>
            <td><?= h($quote->id_formatted) ?></td>
            <td>
                <?= $quote->has('client') ? $this->Html->link($quote->client->name, ['controller' => 'Clients', 'action' => 'view', $quote->client->id]) : '' ?>
            </td>
            <td><?= h($quote->final_price_formatted) ?></td>
            <?php
                $now = (new Time())->i18nFormat([\IntlDateFormatter::SHORT, \IntlDateFormatter::NONE]);
                $expire = (new Time($quote->expire_date))->i18nFormat([\IntlDateFormatter::SHORT, \IntlDateFormatter::NONE]);
                if($now > $expire && !$quote->isAccepted()){
                    $style_field_expire_formatted = 'bg-danger';
                } else if($now == $expire && !$quote->isAccepted()){
                    $style_field_expire_formatted = 'bg-warning';
                } else {
                    $style_field_expire_formatted = 'bg-success';
                }
            ?>
            <td class="<?= $style_field_expire_formatted ?>"><?= h($quote->expire_date_formatted) ?></td>
            <?php
               $tick = $quote->isAccepted() ? 'ok' : 'remove';
            ?>
            <td class="<?= $style_field_expire_formatted ?>"><i class="glyphicon glyphicon-<?= $tick ?>"></i></td>
            <td class="actions">
                <?php if($quote->isAccepted() && $quote->becameOrder()): ?>
                <?= $this->Html->link('', ['controller' => 'Orders', 'action' => 'view', $quote->order_id], ['title' => __('View generated order'), 'class' => 'btn btn-default glyphicon glyphicon-barcode']) ?>
                <?php elseif($quote->isAccepted()): ?>
                <?= $this->Form->postLink('', ['action' => 'generate_order', $quote->id], ['confirm' => __('Are you sure?'), 'title' => __('Generate order from this quote'), 'class' => 'btn btn-default glyphicon glyphicon-list-alt']) ?>
                <?php else: ?>
                <?= $this->Form->postLink('', ['action' => 'set_as_accepted', $quote->id], ['confirm' => __('Are you sure?'), 'title' => __('Set as accepted'), 'class' => 'btn btn-default glyphicon glyphicon-check']) ?>
                <?php endif; ?>
                <?= $this->Html->link('', ['action' => 'view', $quote->id], ['title' => __('View'), 'class' => 'btn btn-default glyphicon glyphicon-eye-open']) ?>
                <?= $this->Form->postLink('', ['action' => 'delete', $quote->id], ['confirm' => __('Are you sure you want to delete # {0}?', $quote->id), 'title' => __('Delete'), 'class' => 'btn btn-default glyphicon glyphicon-trash']) ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="paginator">
    <ul class="pagination">
        <?= $this->Paginator->prev('< ' . __('previous')) ?>
        <?= $this->Paginator->numbers(['before' => '', 'after' => '']) ?>
        <?= $this->Paginator->next(__('next') . ' >') ?>
    </ul>
    <p><?= $this->Paginator->counter() ?></p>
</div>

src/Template/Quotes/view.ctp
<?php

use Cake\Routing\Router;

$this->extend('../Layout/TwitterBootstrap/dashboard');
$this->start('tb_actions');
?>
<li><?= $this->Form->postLink(__('Delete Quote'), ['action' => 'delete', $quote->id], ['confirm' => __('Are you sure you want to delete # {0}?', $quote->id)]) ?> </li>
<?php if($quote->isAccepted() && $quote->becameOrder()): ?>
<li><?= $this->Html->link(__('View generated order'), ['controller' => 'Orders', 'action' => 'view', $quote->order_id]) ?></li>
<?php elseif($quote->isAccepted()): ?>
<li><?= $this->Form->postLink(__('Generate order from this quote'), ['action' => 'generate_order', $quote->id], ['confirm' => __('Are you sure?')]) ?></li>
<?php else: ?>
<li><?= $this->Form->postLink(__('Set as accepted'), ['action' => 'set_as_accepted', $quote->id], ['confirm' => __('Are you sure?')]) ?></li>
<?php endif; ?>
<?php if(is_null($quote->pdf_path)): ?>
<li><?= $this->Form->postLink(__('Generate PDF'), ['action' => 'generate_pdf', $quote->id]) ?> </li>
<?php endif; ?>
<li><?= $this->Html->link(__('New Quote'), ['controller' => 'Quotes', 'action' => 'add']) ?> </li>
<?php $this->end(); ?>
<?php $this->assign('tb_sidebar', '<ul class="nav nav-sidebar">' . $this->fetch('tb_actions') . '</ul>'); ?>

<div class="panel panel-default">
    <!-- Panel header -->
    <div class="panel-heading">
        <h3 class="panel-title"><?= __("Quote to {0}", $quote->client->name) ?></h3>
    </div>
    <table class="table table-striped" cellpadding="0" cellspacing="0">
        <tr>
            <td><?= __('Client') ?></td>
            <td><?= $quote->has('client') ? $this->Html->link($quote->client->identifier, ['controller' => 'Clients', 'action' => 'view', $quote->client->id]) : '' ?></td>
        </tr>
        <tr>
            <td><?= __('Id') ?></td>
            <td><?= h($quote->id_formatted) ?></td>
        </tr>
        <tr>
            <td><?= __('Accepted') ?></td>
            <?php
               if($quote->isAccepted()):
            ?>
            <td><i class="glyphicon glyphicon-ok"></i> <?= $quote->accepted_formatted ?></td>
            <?php else: ?>
            <td><i class="glyphicon glyphicon-remove"></i></td>
            <?php endif; ?>
        </tr>
        <tr>
            <td><?= __('Final Price') ?></td>
            <td><?= h($quote->final_price_formatted) ?></td>
        </tr>
        <tr>
            <td><?= __('Expire Date') ?></td>
            <td><?= h($quote->expire_date_formatted) ?></td>
        </tr>
        <tr>
            <td><?= __('Exit Date') ?></td>
            <td><?= h($quote->exit_date_formatted) ?></td>
        </tr>
        <tr>
            <td><?= __('Created') ?></td>
            <td><?= h($quote->created) ?></td>
        </tr>
    <?php if(!empty($quote->pdf_path)): ?>
        <tr>
            <td colspan="1"><?= __('Attachment') ?></td>
            <?php
                $pdf_name = __("Quote {0} - {1}", $quote->id_formatted, $quote->client->name);
            ?>
            <td colspan="1"><?= $this->Html->link(__('Download'), $quote->pdf_path, ['download' => $pdf_name . '.pdf']) ?></td>
        </tr>
        <tr>
            <td colspan="2">
                <embed width="100%" height="600" src="<?php echo Router::url($quote->pdf_path) ?>" type="application/pdf">            </embed>
            </td>
        </tr>
    <?php else: ?>
        <tr>
            <td><?= __('Warranty') ?></td>
            <td><?= h(nl2br($quote->warranty)) ?></td>
        </tr>
        <tr>
            <td><?= __('Location') ?></td>
            <td><?= h(nl2br($quote->location)) ?></td>
        </tr>
        <tr>
            <td colspan="2"><?= __('Data of the products') ?></td>
        </tr>
        <tr>
            <td colspan="2">
                <table class="table">
                    <thead>
                        <tr>
                            <td style="width: 10%" ><label><?php echo __('Id') ?></label></td>
                            <td style="width: 40%"><label><?php echo __('Name') ?></label></td>
                            <td style="width: 8%" ><label><?php echo __('Quantity') ?></label></td>
                            <td style="width: 10%" ><label><?php echo __('Price Unit') ?></label></td>
                            <td style="width: 14%" ><label><?php echo __('Total Price') ?></label></td>
                        </tr>
                    </thead>
                    <tbody>
                        <?= $this->Html->tableCells($quote->data) ?>
                    </tbody>
                </table>
            </td>
        </tr>
    <?php endif; ?>
    </table>
</div>